// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;

namespace DndExplorer.Tests
{
    public class SuiteTests : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }
        public SuiteTests()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }
        public void Dispose()
        {
            driver.Quit();
        }
        [Fact]
        public void TestForDnDExplorer()
        {
            driver.Navigate().GoToUrl("https://localhost:7233/");
            driver.Manage().Window.Size = new System.Drawing.Size(1066, 808);
            driver.FindElement(By.CssSelector(".btn:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn-secondary:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).SendKeys("human");
            driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".hover-card")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
            {
                var dropdown = driver.FindElement(By.CssSelector(".form-control:nth-child(2)"));
                dropdown.FindElement(By.XPath("//option[. = 'Classes']")).Click();
            }
            driver.FindElement(By.CssSelector(".btn-primary:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn-secondary:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).SendKeys("paladin");
            driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".hover-card")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
            {
                var dropdown = driver.FindElement(By.CssSelector(".form-control:nth-child(2)"));
                dropdown.FindElement(By.XPath("//option[. = 'Spells']")).Click();
            }
            driver.FindElement(By.CssSelector(".btn-primary:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(4) > strong")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).SendKeys("blast");
            driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
            {
                var dropdown = driver.FindElement(By.CssSelector(".form-control:nth-child(2)"));
                dropdown.FindElement(By.XPath("//option[. = 'Monsters']")).Click();
            }
            driver.FindElement(By.CssSelector(".btn-primary:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(3) > strong")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".btn:nth-child(7)"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".btn:nth-child(6)"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).SendKeys("owlbear");
            driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".hover-card")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
            {
                var dropdown = driver.FindElement(By.CssSelector(".form-control:nth-child(2)"));
                dropdown.FindElement(By.XPath("//option[. = 'Equipment']")).Click();
            }
            driver.FindElement(By.CssSelector(".btn-primary:nth-child(3)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(4) > strong")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".btn:nth-child(7)"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".btn:nth-child(6)"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(4)")).SendKeys("sword");
            driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
            driver.FindElement(By.CssSelector(".card-body:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector(".form-control:nth-child(2)")).Click();
        }
    }
}
